notifications:
  sound: "../sound.wav" #Toast can cancel this sound
  toast: true
accounts:
  accountname:
    username: "username"
    password: "password"
  anotheraccountname:
    username: "username"
    password: "password"