name: Prevent config file change
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
      
jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent file change
        uses: xalvarez/prevent-file-change-action@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: .*.yaml
          trustedAuthors: LeagueOfPoro
